image: mcr.microsoft.com/dotnet/sdk:latest
variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  PackageOutputPath: ./_out/pack
  LogPath: ./_out/log
build:
  stage: build
  script:
    - dotnet pack /bl:"$LogPath/build.binlog"
  artifacts:
   when: always
   expire_in: 1 day #we push everything to Artifactory, so we don't need to keep the build output for longer than one day
   paths:
     - NuGet.Config  #keep the NuGet.Config because thats the only thing we need for a package based test. We don't need to map the sources in further stages anymore.
     - _root
     - $LogPath/*.*
     - $PackageOutputPath/*.*

test:
  stage: test
  dependencies:
    - build  #we depend on the build and pack stage, we only want to run when its successful, and we need its artifacts
  script:
    - dotnet test /bl:"$LogPath/test.binlog"

push:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - dotnet build /t:Push /bl:"$LogPath/push.binlog"
