name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:latest
    env:
     PackageOutputPath: ./_out/pack
     LogPath: ./_out/log
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet pack /bl:"$LogPath/build.binlog"
    - name: Test
      run: dotnet test /bl:"$LogPath/test.binlog"
    - name: Push
      run: dotnet build /t:Push /bl:"$LogPath/push.binlog"
      env: # Or as an environment variable
       Nuget_Push_NugetOrgRepository_Token: ${{ secrets.Nuget_Push_NugetOrgRepository_Token }}
